# Dependencies update configuration

version: 2
updates:
  - package-ecosystem: "github-actions"
    reviewers:
      - "hizumiaoba"
    directory: "/.github/workflows"
    target-branch: "main"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
  - package-ecosystem: "gradle"
    reviewers:
      - "hizumiaoba"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
