name: "Continuous Testing with Gradle CI"
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Testing with Gradle"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repo"
        uses: "actions/checkout@v2"
      - name: "Set up JDK 17"
        uses: "actions/setup-java@v2"
        with:
          java-version: "17"
      - name: "Grant execute permission for gradlew"
        run: "chmod +x gradlew"
      - name: "Run tests with Gradle"
        uses: "gradle/gradle-build-action@v2"
        with:
          arguments: |
            test
            -i
            --scan
            --stacktrace
            --refresh-dependencies
