name: "Continuous Testing with Gradle CI"
on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

jobs:
  test:
    name: "Testing with Gradle"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repo"
        uses: "actions/checkout@v4"
      - name: "Set up JDK 17"
        uses: "actions/setup-java@v3"
        with:
          distribution: "temurin"
          java-version: "17"
      - name: "Grant execute permission for gradlew"
        run: "chmod +x gradlew"
      - name: "Run tests with Gradle"
        uses: "gradle/gradle-build-action@v2"
        with:
          arguments: |
            test
            -i
            --scan
            --stacktrace
            --build-cache
  build:
    name: "Building check with Gradle"
    runs-on: "ubuntu-latest"
    needs:
      - test
    steps:
      - name: "Checkout the repo"
        uses: "actions/checkout@v4"
      - name: "Set up JDK 17"
        uses: "actions/setup-java@v3"
        with:
          distribution: "temurin"
          java-version: "17"
      - name: "Grant execute permission for gradlew"
        run: "chmod +x gradlew"
      - name: "Build with Gradle"
        uses: "gradle/gradle-build-action@v2"
        with:
          arguments: |
            build
            -i
            --scan
            --stacktrace
            --build-cache
